#include <iostream>
#include <stdlib.h>
#include<cstdlib>
#include <ctime>
using namespace std;

/*
Write a program that sets up an overloaded function set called GetRandomNum. 
These functions return a random number that is generated with stdlib.h’s srand() and rand(). 
You will need to use the modulus function to do a little math to obtain the desired results. 
There are three different prototypes for the GetRandomNum function:

(i) Pass in a positive integer m and it returns an integer value between 0 and m-1.
int GetRandomNum(int m);
(ii) Pass in two integers (assume i and j are zero or positive and i < j) and receive a random integer between but not including i and j.
int GetRandom(int i, int j);
(iii) Void call returns a random number between 0.000 and 1.000. Assume that three digits of
precision are necessary.
double GetRandom();

Your program should make three calls to GetRandom: once obtaining a number between 0 and
27, once obtaining a number between 3 and 73, and last obtaining a number between 0.0 and
1.0. Write all three numbers to the screen.
*/

int GetRandomNum(int m);
int GetRandom(int i, int j);
double GetRandom();

int main()
{
	int temp1;
	temp1 = GetRandomNum(27); //27 is the integer passed in.
	cout << "The random number generated by the GetRandomNum function is: "<< temp1 << endl;

	int temp2;
	temp2 = GetRandom(3, 73); //3 and 73 are the integers passed in.
	cout << "The random number generated by the GetRandom function is: " << temp2 << endl;

	double temp3;
	temp3 = GetRandom();
	cout.precision(3);
	cout << "The random number generated by the GetRandom float function is: " << temp3 << endl; 

	system("Pause");

}


int GetRandomNum(int m)
{
	int output;
	output = (rand() % m);

/*
rand() function generates random number and when you use rand()%10, 
it will give you last digit of the number. 

Since we require random number between 1 and 10,
we have used rand()%10+1 to generate random number between 1 and 10 in C++.
*/
	return output;
}

int GetRandom(int i, int j)
{
	int output1;
	output1 = (rand() % j) + i;

/*
Since we require random number between i and j,
we have used rand()%10+1 to generate random number between i and j in C++
	return output1;
*/
	return output1;
}

double GetRandom()
{
	double output2;
    output2 = (double)rand()/(RAND_MAX)+0 +(rand()%1);
	return output2;
}